---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/teams":
    get:
      summary: Retrieves all teams
      tags:
      - Teams
      responses:
        '200':
          description: teams found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                  required:
                  - id
                  - name
    post:
      summary: Creates a team
      tags:
      - Teams
      parameters: []
      responses:
        '200':
          description: team created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/teams/{id}":
    get:
      summary: Retrieves a specific team
      tags:
      - Teams
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: team found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                required:
                - id
                - name
    put:
      summary: Updates a team
      tags:
      - Teams
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: team updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    delete:
      summary: Deletes a team
      tags:
      - Teams
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: team deleted
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
